### ISSUE TITLE
Have Some Problem On MacOS M1

### ISSUE THREAD

**Issue by MrRightLi** [big-data-europe/docker-hadoop#136]
docker-compose logs hive-metastore-postgresql
Attaching to docker-hadoop-spark-hive_hive-metastore-postgresql_1
hive-metastore-postgresql_1  | runtime: failed to create new OS thread (have 2 already; errno=22)
hive-metastore-postgresql_1  | fatal error: newosproc
hive-metastore-postgresql_1  |
hive-metastore-postgresql_1  | runtime stack:
hive-metastore-postgresql_1  | runtime.throw(0x524da0, 0x9)
hive-metastore-postgresql_1  | 	/usr/local/go/src/runtime/panic.go:527 +0x90
hive-metastore-postgresql_1  | runtime.newosproc(0xc820028000, 0xc820037fc0)
hive-metastore-postgresql_1  | 	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
hive-metastore-postgresql_1  | runtime.newm(0x555ce8, 0x0)
hive-metastore-postgresql_1  | 	/usr/local/go/src/runtime/proc1.go:1105 +0x130
hive-metastore-postgresql_1  | runtime.main.func1()
hive-metastore-postgresql_1  | 	/usr/local/go/src/runtime/proc.go:48 +0x2c
hive-metastore-postgresql_1  | runtime.systemstack(0x5c4300)
hive-metastore-postgresql_1  | 	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
hive-metastore-postgresql_1  | runtime.mstart()
hive-metastore-postgresql_1  | 	/usr/local/go/src/runtime/proc1.go:674
hive-metastore-postgresql_1  |
hive-metastore-postgresql_1  | goroutine 1 [running]:
hive-metastore-postgresql_1  | runtime.systemstack_switch()
hive-metastore-postgresql_1  | 	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820022770 sp=0xc820022768
hive-metastore-postgresql_1  | runtime.main()
hive-metastore-postgresql_1  | 	/usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200227c0 sp=0xc820022770
hive-metastore-postgresql_1  | runtime.goexit()
hive-metastore-postgresql_1  | 	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200227c8 sp=0xc8200227c0

**Comment by lornafay** [comment]
The images pulled seem to be for x86 architecture according to the DockerHub listing. I used https://github.com/wxw-matt/docker-hadoop for M1 as they are build for ARM64, suggest you try the same.
