### ISSUE TITLE
There are 1 datanode(s) running and 1 node(s) are excluded in this operation. 

### ISSUE THREAD

**Issue by MrHurt** [big-data-europe/docker-hadoop#38]
*问题（question）：*
  不能写入（can't put ）  hdfs://localhost:9000/work/test.txt
*报错如下（error log as follow）：*
```log
namenode_1                   | java.io.IOException: File /work/test.txt could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and 1 node(s) are excluded in this operation.
namenode_1                   |  at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1628)
namenode_1                   |  at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getNewBlockTargets(FSNamesystem.java:3121)
namenode_1                   |  at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3045)
namenode_1                   |  at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:725)
namenode_1                   |  at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:493)
namenode_1                   |  at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
namenode_1                   |  at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
namenode_1                   |  at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
namenode_1                   |  at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
namenode_1                   |  at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
namenode_1                   |  at java.security.AccessController.doPrivileged(Native Method)
namenode_1                   |  at javax.security.auth.Subject.doAs(Subject.java:422)
namenode_1                   |  at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
namenode_1                   |  at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2213)

```
有遇到相同问题的吗？ 
Thanks

**Comment by c1rew** [comment]
@MrHurt 
I encounter the same situation, if you use the virtual machine, you need to expose datanode address ports

**Comment by bdemailly** [comment]
Same for me, expose datanode port 9866 like @MrHurt 

@MrHurt but do you know how to do with 2 datanode? It is not possible to map the same port

**Comment by bdemailly** [comment]
Same for me, expose datanode port 9866 like @c1rew 

@c1rew but do you know how to do with 2 datanode? It is not possible to map the same port

**Comment by c1rew** [comment]
actually, 2 datanode is impossible, to host, cannot bind the same port for
to container, you need to use two real 'datanode', two virtual machines may
be ok.

bdemailly <notifications@github.com> 于2020年4月24日周五 下午11:53写道：

**Comment by bde27** [comment]
Thank you a lot for your reply.

The solution to open port 9864 works when you want to write from the server hosting the hadoop cluster. Cool, thank you!

But when I try to write from an external server, it doesn't work and I get the same error.

Do you have an idea?

**Comment by c1rew** [comment]
> Thank you a lot for your reply.
> 
> The solution to open port 9864 works when you want to write from the server hosting the hadoop cluster. Cool, thank you!
> 
> But when I try to write from an external server, it doesn't work and I get the same error.
> 
> Do you have an idea?

if you really want to fix this problem, you can debug the code, then you will find the answer.

when the request reach host, it can not known container ip, you need to write host information in /etc/host

**Comment by bde27** [comment]
The problem was not with the Hadoop cluster but with the parameters used by default when writing.

The parameters "dfs.client.use.datanode.hostname" and "dfs.datanode.use.datanode.hostname" must be forced to true when writing an external program.
Otherwise the internal IP of the server is used by the external server, and not the hostnames.

thank you for your help.

**Comment by mystic-cg** [comment]
Set `dfs.client.use.datanode.hostname` and `dfs.datanode.use.datanode.hostname`, it still throws error.

Anyone has any idea? 

```java
package individual.cy.hadoop;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;

import java.io.IOException;
import java.net.URI;

/**
 * @author mystic
 */
public class HdfsClient {

    public static void main(String[] args) {
        URI uri = URI.create("hdfs://127.0.0.1:9864");
        Configuration conf = new Configuration();
        conf.set("dfs.client.use.datanode.hostname", "true");
        conf.set("dfs.datanode.use.datanode.hostname", "true");

        Path src = new Path("file:///C:\\Users\\test.txt");
        Path dest = new Path("/var/tmp/");
        try (FileSystem fs = FileSystem.get(uri, conf, "root")) {
            fs.copyFromLocalFile(src, dest);
        } catch (InterruptedException | IOException e) {
            e.printStackTrace();
        }
    }
}

```
It throws the following error:
`RPC response exceeds maximum data length`
```text
java.io.IOException: Failed on local exception: org.apache.hadoop.ipc.RpcException: RPC response exceeds maximum data length; Host Details : local host is: "CN-00003938/100.98.219.83"; destination host is: "kubernetes.docker.internal":9864; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:818)
	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1549)
	at org.apache.hadoop.ipc.Client.call(Client.java:1491)
	at org.apache.hadoop.ipc.Client.call(Client.java:1388)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:233)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
	at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:907)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1666)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1573)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1588)
	at org.apache.hadoop.fs.FileUtil.checkDest(FileUtil.java:511)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:397)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:387)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:2369)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:2335)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:2298)
	at individual.cy.hadoop.HdfsClient.main(HdfsClient.java:24)
Caused by: org.apache.hadoop.ipc.RpcException: RPC response exceeds maximum data length
	at org.apache.hadoop.ipc.Client$IpcStreams.readResponse(Client.java:1864)
	at org.apache.hadoop.ipc.Client$Connection.receiveRpcResponse(Client.java:1183)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:1079)
DEBUG [Thread-3] - Completed shutdown in 0.002 seconds; Timeouts: 0
DEBUG [Thread-3] - ShutdownHookManger completed shutdown.

```

**Comment by rodrigo-borges** [comment]
@bde27 aren't these two parameters already forced to true in the entrypoint.sh?

```
...
if [ "$MULTIHOMED_NETWORK" = "1" ]; then
    echo "Configuring for multihomed network"

    # HDFS
    addProperty /etc/hadoop/hdfs-site.xml dfs.namenode.rpc-bind-host 0.0.0.0
    addProperty /etc/hadoop/hdfs-site.xml dfs.namenode.servicerpc-bind-host 0.0.0.0
    addProperty /etc/hadoop/hdfs-site.xml dfs.namenode.http-bind-host 0.0.0.0
    addProperty /etc/hadoop/hdfs-site.xml dfs.namenode.https-bind-host 0.0.0.0
    addProperty /etc/hadoop/hdfs-site.xml dfs.client.use.datanode.hostname true
    addProperty /etc/hadoop/hdfs-site.xml dfs.datanode.use.datanode.hostname true
...
```

I'm facing the same issue when trying to write or read files from pyspark in an external client. Could you please elaborate more on what you did to solve the problem?

**Comment by haydenzhourepo** [comment]
> The problem was not with the Hadoop cluster but with the parameters used by default when writing.
> 
> The parameters "dfs.client.use.datanode.hostname" and "dfs.datanode.use.datanode.hostname" must be forced to true when writing an external program.
> Otherwise the internal IP of the server is used by the external server, and not the hostnames.
> 
> thank you for your help.

The parameters "dfs.client.use.datanode.hostname" and "dfs.datanode.use.datanode.hostname"  be forced to true, not working for me set up hadoop by docker

**Comment by A7Khan** [comment]
Hey guys, 

Has anyone actually got a fix for this or have solved it? I'm facing the same problem with my Hadoop docker. I have run a simple wordcount test to see if everything is working fine, and it does but as soon as I have spark stream writing into it. HDFS doesn't seem to pick them up at all

`2020-12-07 09:20:58.212  WARN 1 --- [ool-22-thread-1] o.a.spark.streaming.CheckpointWriter     : Could not write checkpoint for time 1607332854000 ms to file 'hdfs://namenode:8020/dangerousgoods/checkpoint/checkpoint-1607332858000'


2020-12-07 09:20:58.213  INFO 1 --- [uler-event-loop] o.a.spark.storage.memory.MemoryStore     : Block broadcast_18 stored as values in memory (estimated size 17.2 KB, free 9.2 GB)


2020-12-07 09:20:58.214  INFO 1 --- [uler-event-loop] o.a.spark.storage.memory.MemoryStore     : Block broadcast_18_piece0 stored as bytes in memory (estimated size 7.4 KB, free 9.2 GB)


2020-12-07 09:20:58.214  INFO 1 --- [er-event-loop-8] o.apache.spark.storage.BlockManagerInfo  : Added broadcast_18_piece0 in memory on 16b1f170f11c:42679 (size: 7.4 KB, free: 9.2 GB)


2020-12-07 09:20:58.215  INFO 1 --- [uler-event-loop] org.apache.spark.SparkContext            : Created broadcast 18 from broadcast at DAGScheduler.scala:1163


2020-12-07 09:20:58.215  INFO 1 --- [uler-event-loop] org.apache.spark.scheduler.DAGScheduler  : Submitting 1 missing tasks from ShuffleMapStage 53 (MapPartitionsRDD[28] at mapToPair at RealtimeProcessor.java:256) (first 15 tasks are for partitions Vector(0))


2020-12-07 09:20:58.215  INFO 1 --- [uler-event-loop] o.a.spark.scheduler.TaskSchedulerImpl    : Adding task set 53.0 with 1 tasks


2020-12-07 09:20:58.216  INFO 1 --- [er-event-loop-7] o.apache.spark.scheduler.TaskSetManager  : Starting task 0.0 in stage 53.0 (TID 19, 10.0.9.185, executor 0, partition 0, PROCESS_LOCAL, 7760 bytes)


2020-12-07 09:20:58.221  INFO 1 --- [r-event-loop-10] o.apache.spark.storage.BlockManagerInfo  : Added broadcast_18_piece0 in memory on 10.0.9.185:38567 (size: 7.4 KB, free: 366.2 MB)


2020-12-07 09:20:58.225  INFO 1 --- [result-getter-0] o.apache.spark.scheduler.TaskSetManager  : Finished task 0.0 in stage 53.0 (TID 19) in 9 ms on 10.0.9.185 (executor 0) (1/1)


2020-12-07 09:20:58.225  INFO 1 --- [result-getter-0] o.a.spark.scheduler.TaskSchedulerImpl    : Removed TaskSet 53.0, whose tasks have all completed, from pool 


2020-12-07 09:20:58.226  INFO 1 --- [uler-event-loop] org.apache.spark.scheduler.DAGScheduler  : ShuffleMapStage 53 (mapToPair at RealtimeProcessor.java:256) finished in 0.014 s


2020-12-07 09:20:58.226  INFO 1 --- [uler-event-loop] org.apache.spark.scheduler.DAGScheduler  : looking for newly runnable stages


2020-12-07 09:20:58.226  INFO 1 --- [uler-event-loop] org.apache.spark.scheduler.DAGScheduler  : running: Set()


2020-12-07 09:20:58.226  INFO 1 --- [uler-event-loop] org.apache.spark.scheduler.DAGScheduler  : waiting: Set(ResultStage 55)


2020-12-07 09:20:58.226  INFO 1 --- [uler-event-loop] org.apache.spark.scheduler.DAGScheduler  : failed: Set()


2020-12-07 09:20:58.227  INFO 1 --- [uler-event-loop] org.apache.spark.scheduler.DAGScheduler  : Submitting ResultStage 55 (MapPartitionsRDD[33] at map at RealtimeProcessor.java:264), which has no missing parents


2020-12-07 09:20:58.227  INFO 1 --- [uler-event-loop] o.a.spark.storage.memory.MemoryStore     : Block broadcast_19 stored as values in memory (estimated size 8.8 KB, free 9.2 GB)


2020-12-07 09:20:58.228  INFO 1 --- [uler-event-loop] o.a.spark.storage.memory.MemoryStore     : Block broadcast_19_piece0 stored as bytes in memory (estimated size 4.4 KB, free 9.2 GB)


2020-12-07 09:20:58.229  INFO 1 --- [er-event-loop-0] o.apache.spark.storage.BlockManagerInfo  : Added broadcast_19_piece0 in memory on 16b1f170f11c:42679 (size: 4.4 KB, free: 9.2 GB)


2020-12-07 09:20:58.229  INFO 1 --- [uler-event-loop] org.apache.spark.SparkContext            : Created broadcast 19 from broadcast at DAGScheduler.scala:1163


2020-12-07 09:20:58.229  INFO 1 --- [uler-event-loop] org.apache.spark.scheduler.DAGScheduler  : Submitting 1 missing tasks from ResultStage 55 (MapPartitionsRDD[33] at map at RealtimeProcessor.java:264) (first 15 tasks are for partitions Vector(0))`

that is the first error that prompts and after few sec, I get the exact same error like this post is titled

**Comment by macknight** [comment]
Hi anyone could fix this issue?
I'm using docker-hub image.
The parameters "dfs.client.use.datanode.hostname" and "dfs.datanode.use.datanode.hostname" are all true in my hdfs-site.xml but it still have that problem.

**Comment by shivanshkaushikk** [comment]
Any update on this issue?

**Comment by fenggolang** [comment]
I encounter the same situation？ when I deploy docker-hadoop image in k8s cluster.

**Comment by shivanshkaushikk** [comment]
> I encounter the same situation？ when I deploy docker-hadoop image in k8s cluster.

just found out that the issue at my end was the connectivity between datanode and my local python app, after deploying my app in the same docker network as hadoop it was solved.

**Comment by AChangFeng** [comment]
If you want to write from external hosts: 

- Open datanode container port 9864 and 9866, then recreate containers.
- Add ```${host ip} datanode namenode ${namenode container id} ${datanode container id}``` to your local hosts file.
- Set client configuration parameter ```dfs.client.use.datanode.hostname``` to ```true```:
```
Configuration().apply {
  this.set("dfs.client.use.datanode.hostname", "true")
}
```


If you do not want to add ```${namenode container id} ${datanode container id}``` to your local hosts file, you can set datanode container hostname to ```datanode``` and namenode container hostname to ```namenode``` by ```hostname``` instruction to container configuraion in ```docker-compose.yaml```:
```
...
namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    hostname: namenode
...
datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    hostname: datanode
...
```

**Comment by geekyouth** [comment]
datax 写入报这个错时，应该使用：
```
"hadoopConfig": {
    "dfs.client.use.datanode.hostname": "true",
    "dfs.datanode.use.datanode.hostname": "true"
}
```
