### ISSUE TITLE
Write HDFS with external server port 9000

### ISSUE THREAD

**Issue by bde27** [big-data-europe/docker-hadoop#67]
Thank you for sharing.

I am trying to write to HDFS from an ElasticSearch cluster via port 9000.
With the mapping port 9866 on datanode and ElasticSearch on the same server it works.

But when ElasticSearch is hosted on a separate server I get this error:
```
File /user/elasticsearch/repositories/backup/tests-drDBcjJtS5ak1AAQEJuRoA/pending-master.dat-PSdMuA6WRl6oJhPK2Ejy9w could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and 1 node(s) are excluded in this operation.
	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2219)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:294)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2789)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:892)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:574)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)
```

There is no firewall between the 2 servers.

Do you have an idea?
Thanks a lot for your help!

**Comment by bde27** [comment]
Problem solved!!

If that helps, the problem is related to ElasticSearch.
By default, ElasticSearch does not use the hdfs-site.xml parameters.

It is therefore necessary to force the use of the desired parameters with ElasticSearch.

Thanks for the project!
