### ISSUE TITLE
Namenode format issue with AWS EBS in EKS cluster

### ISSUE THREAD

**Issue by vishalgoel1988** [big-data-europe/docker-hadoop#69]
Hi,

I have EKS cluster with EBS storage class/volume. I have elasticsearch cluster running fine with this EBS storage.
I am trying to deploy this hdfs namenode image (bde2020/hadoop-namenode) using statefulset, but it gives me below error always:
```
2020-05-09 08:59:02,400 INFO util.GSet: capacity      = 2^15 = 32768 entries
2020-05-09 08:59:02,415 INFO common.Storage: Lock on /hadoop/dfs/name/in_use.lock acquired by nodename 87@hdfs-name-0.hdfs-name.pulse.svc.cluster.local
2020-05-09 08:59:02,417 WARN namenode.FSNamesystem: Encountered exception loading fsimage
java.io.IOException: NameNode is not formatted.
	at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:252)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFSImage(FSNamesystem.java:1105)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFromDisk(FSNamesystem.java:720)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.loadNamesystem(NameNode.java:648)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:710)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:953)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:926)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1692)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1759)
```

I checked run.sh and it does seem to be formatting namenode if dir is empty. But this does not work in may case. Any help would be very appreciated.

My deployment yml is:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-name
  labels:
    component: hdfs-name
spec:
  serviceName: hdfs-name
  replicas: 1
  selector:
    matchLabels:
      component: hdfs-name
  template:
    metadata:
      labels:
        component: hdfs-name
    spec:
      containers:
      - name: hdfs-name
        image: bde2020/hadoop-namenode
        env:
        - name: CLUSTER_NAME
          value: hdfs-k8s
        ports:
        - containerPort: 8020
          name: nn-rpc
        - containerPort: 50070
          name: nn-web
        volumeMounts:
        - name: hdfs-name-pv-claim
          mountPath: /hadoop/dfs/name 
  volumeClaimTemplates:
  - metadata:
      name: hdfs-name-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs
      resources:
        requests:
          storage: 1Gi

```

**Comment by asaklex** [comment]
Your statefulset is fine. I had the same issue due to the fact that the EBS is not empty when created by the Provider. I m using OVH managed Kubernetes. I had to add 2 lines of code to delete lost+found folder right before formating instruction in the run.sh for namenode:

`echo "remove lost+found from $namedir"`
`rm -r $namedir/lost+found`

I have created a custom docker image with the changes here : abdoumediaoptimise/hdfs-namenode

here is my full run.sh:

![image](https://user-images.githubusercontent.com/16624465/81476280-27d18b00-91df-11ea-9889-c20136617b9e.png)

**Comment by asaklex** [comment]
I have also created a pull request[ here ](https://github.com/big-data-europe/docker-hadoop/pull/70)

**Comment by vishalgoel1988** [comment]
Thanks @asaklex . I think this is the issue. I am little bit new to this, but when can I get this updated in  bde2020/hadoop-namenode image?

**Comment by asaklex** [comment]
It depends on Repository admins. While waiting for the merge, try to use this image  to test if it works: 
abdoumediaoptimise/hdfs-namenode

**Comment by vishalgoel1988** [comment]
Having initcontainer to delete the lost+found folder seems to work. Thank you again for help.
Also, I have one more issue, I don't see 50070 port being opened. It is not even there in logs. Any help here please?

**Comment by vishalgoel1988** [comment]
My bad, hdfs 3.1x starts namenode web on 9870.
