### ISSUE TITLE
java client raises `java.net.UnknownHostException: can not resolve hbase-master`

### ISSUE THREAD

**Issue by diegoquintanav** [big-data-europe/docker-hadoop#78]
How should I connect a client using the java API?. I'm using this at the moment this gist

```java
Configuration config = HBaseConfiguration.create();
config.set("hbase.zookeeper.quorum", "localhost");
config.set("hbase.zookeeper.property.clientPort", "2181");
HBaseAdmin.available(config);
```

Returns 

```java
org.apache.hadoop.hbase.MasterNotRunningException: org.apache.hadoop.hbase.MasterNotRunningException: java.net.UnknownHostException: can not resolve hbase-master,16000,1592488743309
	at org.apache.hadoop.hbase.client.ConnectionImplementation.isMasterRunning(ConnectionImplementation.java:610)
	at org.apache.hadoop.hbase.client.HBaseAdmin.available(HBaseAdmin.java:2410)
	at Main.main(Main.java:95)
```

How should I fix this?

---
I'm using `hbase-client` 2.2.5, but version 1.6.0 rises the same problem.

```
        <!-- https://mvnrepository.com/artifact/org.apache.hbase/hbase-client -->
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-client</artifactId>
            <version>2.2.5</version>
        </dependency>
```

**Comment by diegoquintanav** [comment]
I wanted to post this in docker-hbase, lol
