### ISSUE TITLE
Hadoop3 ha volume problem

### ISSUE THREAD

**Issue by ktpktr0** [big-data-europe/docker-hadoop#89]
I noticed that the current Hadoop distributed cluster is not highly available and there is a single point of failure between namenode and ResourceManager, so I tried to configure high availability.

HDFS_ CONF_ dfs_ nameservices=ns
HDFS_ CONF_ dfs_ Ha_ namenodes_ ns=nn1,nn2
HDFS_ CONF_ dfs_ namenode_ rpc___ address_ ns_ nn1=namenode1:8020
HDFS_ CONF_ dfs_ namenode_ rpc___ address_ ns_ nn2=namenode2:8020
HDFS_ CONF_ dfs_ namenode_ http___ address_ ns_ nn1=namenode1:9870
HDFS_ CONF_ dfs_ namenode_ http___ address_ ns_ nn2=namenode2:9870
HDFS_ CONF_ dfs_ namenode_ shared_ edits_ dir= qjournal://journalnode1 :8485;journalnode2:8485;journalnode3:8485/ns

I got the following errors:

2020-10-21 07:42:12,007 INFO common.Storage: Lock on /hadoop/dfs/name/in_use.lock acquired by nodename 443@35cff388ca4f,
2020-10-21 07:42:12,024 WARN namenode.FSNamesystem: Encountered exception loading fsimage,
java.io.FileNotFoundException: No valid image files found,
at org.apache.hadoop.hdfs.server.namenode.FSImageTransactionalStorageInspector.getLatestImages(FSImageTransactionalStorageInspector.java:158),
at org.apache.hadoop.hdfs.server.namenode.FSImage.loadFSImage(FSImage.java:687),
at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:338),
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFSImage(FSNamesystem.java:1105),
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFromDisk(FSNamesystem.java:720),
at org.apache.hadoop.hdfs.server.namenode.NameNode.loadNamesystem(NameNode.java:648),
at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:710),
at org.apache.hadoop.hdfs.server.namenode.NameNode.(NameNode.java:953),
at org.apache.hadoop.hdfs.server.namenode.NameNode.(NameNode.java:926),
at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1692),
at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1759),

I judge that the namenode or resource manager data between different nodes of docker volume cannot be shared. Do you need shared storage such as NFS to solve the problems mentioned above.

@earthquakesan

**Comment by earthquakesan** [comment]
@ktpktr0 that's correct, you will have to create named volume inside e.g. docker compose definition and mount it to both docker containers to have shared volume. This won't work well in multi-node deployment though.

**Comment by ktpktr0** [comment]
@earthquakesan I don't know which way is correct，Datanode and nodemanager are in global mode, how their files are synchronized. Why do namenode and journalnode not work like them in ha mode

1、The first time I tried, but I don’t know how to configure the hostname of nn1 and nn2 in hadoop

version: '3.2'

services:
  namenode:
    image: test/hadoop-namenode:2.0.0-hadoop2.7.7-java8
    networks:
      - bigdata
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop5.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == test3
      labels:
        traefik.docker.network: bigdata
        traefik.port: 9870

  datanode:
    image: test/hadoop-datanode:2.0.0-hadoop2.7.7-java8
    networks:
      - bigdata
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop5.env
    environment:
      SERVICE_PRECONDITION: "namenode1:9870 namenode2:9870"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata
        traefik.port: 9864

  journalnode:
    image: test/hadoop-journalnode:2.0.0-hadoop2.7.7-java8
    networks:
      - bigdata
    volumes:
      - journalnode:/hadoop/dfs/journalnode
    env_file:
      - ./hadoop5.env
    #environment:
    #  SERVICE_PRECONDITION: "namenode1:9870 namenode2:9870"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata
        traefik.port: 8485

hadoop.env:

HDFS_CONF_dfs_nameservices=ns
HDFS_CONF_dfs_ha_namenodes_ns=nn1,nn2
HDFS_CONF_dfs_namenode_rpc___address_ns_nn1=namenode:8020
HDFS_CONF_dfs_namenode_rpc___address_ns_nn2=namenode:8020
HDFS_CONF_dfs_namenode_http___address_ns_nn1=namenode:9870
HDFS_CONF_dfs_namenode_http___address_ns_nn2=namenode:9870
HDFS_CONF_dfs_namenode_shared_edits_dir=qjournal://journalnode:8485/ns
HDFS_CONF_dfs_ha_automatic___failover_enabled=true
HDFS_CONF_dfs_client_failover_proxy_provider_ns=org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
HDFS_CONF_dfs_ha_fencing_methods=shell(/bin/true)
HDFS_CONF_dfs_ha_fencing_ssh_private___key___files=/root/.ssh/id_rsa
HDFS_CONF_dfs_journalnode_edits_dir=/hadoop/dfs/journalnode

CORE_CONF_fs_defaultFS=hdfs://ns:9000


2、Second attempt

version: '3.2'

services:
  namenode1:
    image: test/hadoop-namenode:2.0.0-hadoop2.7.7-java8
    networks:
      - bigdata
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: test
    env_file:
      - ./hadoop3.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == test3
      labels:
        traefik.docker.network: bigdata
        traefik.port: 9870

  namenode2:
    image: test/hadoop-namenode:2.0.0-hadoop2.7.7-java8
    networks:
      - bigdata
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
       CLUSTER_NAME: test
       SERVICE_PRECONDITION: "namenode1:9870"
    env_file:
      - ./hadoop3.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == test3
      labels:
        traefik.docker.network: bigdata
        traefik.port: 9870

  datanode:
    image: test/hadoop-datanode:2.0.0-hadoop2.7.7-java8
    networks:
      - bigdata
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop3.env
    environment:
      SERVICE_PRECONDITION: "namenode1:9870 namenode2:9870"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata
        traefik.port: 9864

  journalnode1:
    image: test/hadoop-journalnode:2.0.0-hadoop2.7.7-java8
    networks:
      - bigdata
    volumes:
      - journalnode:/hadoop/dfs/journalnode
    env_file:
      - ./hadoop3.env
    #environment:
    #  SERVICE_PRECONDITION: "namenode1:9870 namenode2:9870"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata
        traefik.port: 8485

  journalnode2:
    image: test/hadoop-journalnode:2.0.0-hadoop2.7.7-java8
    networks:
      - bigdata
    volumes:
      - journalnode:/hadoop/dfs/journalnode
    env_file:
      - ./hadoop3.env
    #environment:
    #  SERVICE_PRECONDITION: "namenode1:9870 namenode2:9870"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata
        traefik.port: 8485

  journalnode3:
    image: test/hadoop-journalnode:2.0.0-hadoop2.7.7-java8
    networks:
      - bigdata
    volumes:
      - journalnode:/hadoop/dfs/journalnode
    env_file:
      - ./hadoop3.env
    #environment:
    #  SERVICE_PRECONDITION: "namenode1:9870 namenode2:9870"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata
        traefik.port: 8485

hadoop.env:

HDFS_ CONF_ dfs_ nameservices=ns
HDFS_ CONF_ dfs_ Ha_ namenodes_ ns=nn1,nn2
HDFS_ CONF_ dfs_ namenode_ rpc___ address_ ns_ nn1=namenode1:8020
HDFS_ CONF_ dfs_ namenode_ rpc___ address_ ns_ nn2=namenode2:8020
HDFS_ CONF_ dfs_ namenode_ http___ address_ ns_ nn1=namenode1:9870
HDFS_ CONF_ dfs_ namenode_ http___ address_ ns_ nn2=namenode2:9870
HDFS_ CONF_ dfs_ namenode_ shared_ edits_ dir= qjournal://journalnode1 :8485;journalnode2:8485;journalnode3:8485/ns

**Comment by ktpktr0** [comment]
@earthquakesan Excuse me again, Is it necessary for zkfc to run with namenode. I tried to copy the configuration (HDFS) of namenode- site.xml 、core- site.xml ）With namenode disk and then starting a container to run zkfc, I got the following error:

2020-11-03 06:58:55,581 INFO tools.DFSZKFailoverController : registered UNIX signal handlers for [TERM, HUP, INT]
2020-11-03 06:58:55,784 ERROR tools.DFSZKFailoverController : DFSZKFailOverController exiting due to earlier exception org.apache.hadoop .HadoopIllegalArgumentException: Could not get the namenode ID of this node. You may run zkfc on the node other than namenode.

2020-11-03 06:58:55,787 INFO util.ExitUtil : Exiting with status 1: org.apache.hadoop .HadoopIllegalArgumentException: Could not get the namenode ID of this node. You may run zkfc on the node other than namenode.

2020-11-03 06:58:55,789 INFO tools.DFSZKFailoverController : SHUTDOWN_ MSG:

When I run zkfc in the namenode container normally. What's a good way to run zkfc in a separate container?
